github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: https
    user: vivi870123
    oauth_token: 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
