github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: vivi870123
