github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: ssh
    user: vivi870123
    oauth_token: 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
