github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: https
    user: vivi870123
    oauth_token: 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
