github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: https
    user: vivi870123
    oauth_token: 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
