github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: https
    user: vivi870123
    oauth_token: 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
