# vim:ft=zsh

# set LANG
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

# Default programs:
export EDITOR="nvim"
export BROWSER="org.mozilla.firefox"
export READER="zathura"
export FILE="lf"
export MUSIC="cmus"
export AUDIO="pulsemixer"
export PROCESS="htop"
export TORRENT="transmission-remote-gtk"

export TERMINAL="foot"
export RUN_LAUNCHER="bemenu-run"
export MENU="bemenu"
export BUS_BROWSER="brave --ozone-platform=wayland"
export MOZ_ENABLE_WAYLAND=1
export WMBLOCKS="someblocks"
export BEMENU_BACKEND="wayland"
export MOZ_DBUS_REMOTE=1 # fixes firefox is already running, but is not responding
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_AWT_WM_NONREPARENTING=1

export NOTES_DIR="~/Documents/notes"
export SYNC_DIR="$HOME/Dropbox"
export DOTFILES="$HOME/.dotfiles"
export PROJECTS_DIR="$HOME/projects"
export PROJECTS="$HOME/projects"
export PERSONAL_PROJECTS_DIR="$PROJECTS_DIR/personal"
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

### XDG ###
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

### ZSH ###
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"
export SHELDON_CONFIG_DIR="$ZDOTDIR"

### GO ###
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GO111MODULE="on"

### RUST ###
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

### Deno ###
export DENO_INSTALL="$XDG_DATA_HOME/deno"
export DENO_INSTALL_ROOT="$DENO_INSTALL"
