github.com:
    users:
        vivi870123:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: vivi870123
